services:

  broker:
    image: 'eclipse-mosquitto:latest'
    ports:
      - '1883:1883'
    healthcheck:
      test: ["CMD", "wget", "http://localhost:1883", "-O", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
    # Uncomment and configure to store data in a mapped directory on host
    # volumes:
      # - /mnt/c/dev/tmp/nightscout/data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5

  nightscout:
    image: 'nightscout/cgm-remote-monitor'
    environment:
      - API_SECRET=${API_SECRET}
      - 'MONGO_CONNECTION=mongodb://admin:${MONGODB_PASS}@database/admin'
      - 'MQTT_MONITOR=mqtt://${MONGODB_PASS}@broker'
      - PORT=1337
      - INSECURE_USE_HTTP=true # We are using a SSL proxy for HTTPS
      - AUTH_DEFAULT_ROLES=denied
      - 'ENABLE=careportal basal Iob Cob Bwp Ar2 boluscalc cage sage iage pump cors openaps'
      - TIME_FORMAT=24
    restart: on-failure
    depends_on:
      - broker
      - database
    links:
      - broker
      - database
    ports:
      - '1337:1337'
